/**
 * Snapshot of the 2026-08-25/26 audits (portability + cartography). Not a
 * live scan: any DS change since this date won't be reflected here until
 * the file is regenerated by hand.
 */

export type ComponentStatus = 'core' | 'niche' | 'orphan' | 'duplicate' | 'internal';

export interface DsComponentEntry {
  /** Display name, e.g. "Button". */
  name: string;
  /** Folder under shared/ui. */
  folder: string;
  /** Storybook category (2nd segment of the title) or a deduced one. */
  category: string;
  /** Exact Storybook title (meta.title), null if there's no story. */
  storybookTitle: string | null;
  /** false if the story exists but lacks the 'autodocs' tag (less reliable link). */
  hasAutodocs: boolean;
  /** Exact number of consuming pages, when the audit counted it precisely. */
  usageCount: number | null;
  /** Named pages, when known (null = not detailed in the audit). */
  usagePages: string[] | null;
  status: ComponentStatus;
  note?: string;
  /** Folder of the twin component, for duplicates. */
  duplicateOf?: string;
}

export const DS_COMPONENTS: DsComponentEntry[] = [
  // ── Core: strong adoption, story OK ─────────────────────────────────────
  { name: 'Icon', folder: 'icon', category: 'Foundation', storybookTitle: 'Design System/Foundation/Icon', hasAutodocs: true, usageCount: 119, usagePages: null, status: 'core' },
  { name: 'Input Text', folder: 'input-text', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Input Text', hasAutodocs: true, usageCount: 78, usagePages: null, status: 'core' },
  { name: 'Button', folder: 'button', category: 'Action', storybookTitle: 'Design System/Action/Button', hasAutodocs: true, usageCount: 56, usagePages: null, status: 'core' },
  { name: 'Tab', folder: 'tab', category: 'Action', storybookTitle: 'Design System/Action/Tab', hasAutodocs: true, usageCount: 39, usagePages: null, status: 'core' },
  { name: 'Select', folder: 'select', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Select', hasAutodocs: true, usageCount: 36, usagePages: null, status: 'core' },
  { name: 'Flyout Menu Item', folder: 'flyout-menu', category: 'Internals', storybookTitle: 'Design System/Internals/Flyout Menu Item', hasAutodocs: true, usageCount: 36, usagePages: null, status: 'core' },
  { name: 'Button Icon', folder: 'button-icon', category: 'Action', storybookTitle: 'Design System/Action/Button Icon', hasAutodocs: true, usageCount: 32, usagePages: null, status: 'core' },
  { name: 'Crumb', folder: 'crumb', category: 'Action', storybookTitle: 'Design System/Action/Crumb', hasAutodocs: true, usageCount: 29, usagePages: null, status: 'core' },
  { name: 'Cell Header', folder: 'table', category: 'Data Display/Table', storybookTitle: 'Design System/Data Display/Table/Cell Header', hasAutodocs: true, usageCount: 29, usagePages: null, status: 'core' },
  { name: 'Properties Panel', folder: 'properties-panel', category: 'Data Display', storybookTitle: 'Design System/Data Display/Properties Panel', hasAutodocs: true, usageCount: 23, usagePages: null, status: 'core' },
  { name: 'Cell', folder: 'table', category: 'Data Display/Table', storybookTitle: 'Design System/Data Display/Table/Cell', hasAutodocs: true, usageCount: 22, usagePages: null, status: 'core' },
  { name: 'Modal', folder: 'modal', category: 'Layout', storybookTitle: 'Design System/Layout/Modal', hasAutodocs: true, usageCount: 21, usagePages: null, status: 'core' },
  { name: 'Badge', folder: 'badge', category: 'Feedback', storybookTitle: 'Design System/Feedback/Badge', hasAutodocs: true, usageCount: 15, usagePages: null, status: 'core' },
  { name: 'Link', folder: 'link', category: 'Action', storybookTitle: 'Design System/Action/Link', hasAutodocs: true, usageCount: 14, usagePages: null, status: 'core' },
  { name: 'Flyout Menu', folder: 'flyout-menu', category: 'Action', storybookTitle: 'Design System/Action/Flyout Menu', hasAutodocs: true, usageCount: 13, usagePages: null, status: 'core' },
  { name: 'Card', folder: 'card', category: 'Data Display', storybookTitle: 'Design System/Data Display/Card', hasAutodocs: true, usageCount: 12, usagePages: null, status: 'core' },
  { name: 'Widget Card', folder: 'widget-card', category: 'Data Display', storybookTitle: 'Design System/Data Display/Widget Card', hasAutodocs: true, usageCount: 11, usagePages: null, status: 'core' },
  { name: 'Page Header', folder: 'page-header', category: 'Layout', storybookTitle: 'Design System/Layout/Page Header', hasAutodocs: true, usageCount: 9, usagePages: null, status: 'core' },
  { name: 'Breadcrumbs', folder: 'breadcrumbs', category: 'Action', storybookTitle: 'Design System/Action/Breadcrumbs', hasAutodocs: true, usageCount: 9, usagePages: null, status: 'core' },
  { name: 'Table Row', folder: 'table', category: 'Data Display/Table', storybookTitle: 'Design System/Data Display/Table/Table Row', hasAutodocs: true, usageCount: 8, usagePages: null, status: 'core' },
  { name: 'Page Title', folder: 'page-title', category: 'Layout', storybookTitle: 'Design System/Layout/Page Title', hasAutodocs: true, usageCount: 8, usagePages: null, status: 'core' },
  { name: 'Checkbox', folder: 'checkbox', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Checkbox', hasAutodocs: true, usageCount: 7, usagePages: null, status: 'core' },

  // ── Legitimate niche usage (1-2 pages) ───────────────────────────────────
  { name: 'Standalone Dropdown', folder: 'standalone-dropdown', category: 'Action', storybookTitle: 'Design System/Action/Standalone Dropdown', hasAutodocs: true, usageCount: 1, usagePages: ['topbox (demo)'], status: 'niche' },
  { name: 'Side Nav', folder: 'side-nav', category: 'Layout', storybookTitle: 'Design System/Layout/Side Nav', hasAutodocs: true, usageCount: 1, usagePages: ['topbox (demo)'], status: 'niche' },
  { name: 'Logo', folder: 'logo', category: 'Foundation', storybookTitle: 'Design System/Foundation/Logo', hasAutodocs: true, usageCount: 1, usagePages: ['topbox (demo)'], status: 'niche' },
  { name: 'Header', folder: 'header', category: 'Layout', storybookTitle: 'Design System/Layout/Header', hasAutodocs: true, usageCount: 1, usagePages: ['topbox (demo)'], status: 'niche' },
  { name: 'Segmented Control', folder: 'segmented-control', category: 'Action', storybookTitle: 'Design System/Action/Segmented Control', hasAutodocs: true, usageCount: 1, usagePages: ['buyer-summary'], status: 'niche' },
  { name: 'Pie Chart', folder: 'pie-chart', category: 'Data Display', storybookTitle: 'Design System/Data Display/Pie Chart', hasAutodocs: true, usageCount: 1, usagePages: ['buyer-summary'], status: 'niche' },
  { name: 'Newsfeed', folder: 'newsfeed', category: 'Data Display', storybookTitle: 'Design System/Data Display/Newsfeed', hasAutodocs: true, usageCount: 1, usagePages: ['buyer-summary'], status: 'niche' },
  { name: 'Drawer', folder: 'drawer', category: 'Layout', storybookTitle: 'Design System/Layout/Drawer', hasAutodocs: false, usageCount: 1, usagePages: ['buyer-summary'], status: 'niche', note: "Story has no 'autodocs' tag — links to the Default story instead of the docs page." },
  { name: 'Input Search', folder: 'input-search', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Input Search', hasAutodocs: true, usageCount: 1, usagePages: ['buyer-summary'], status: 'niche' },
  { name: 'Grid Selection', folder: 'grid-selection', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Grid Selection', hasAutodocs: true, usageCount: 1, usagePages: ['buyer-summary'], status: 'niche' },
  { name: 'Chart', folder: 'chart', category: 'Data Display', storybookTitle: 'Design System/Data Display/Chart', hasAutodocs: true, usageCount: 1, usagePages: ['buyer-summary'], status: 'niche' },
  { name: 'Grade', folder: 'grade', category: 'Data Display', storybookTitle: 'Design System/Data Display/Grade', hasAutodocs: true, usageCount: 1, usagePages: ['buyer-summary'], status: 'niche' },
  { name: 'Button Split', folder: 'button-split', category: 'Action', storybookTitle: 'Design System/Action/Button Split', hasAutodocs: true, usageCount: 1, usagePages: ['buyer-summary'], status: 'niche' },
  { name: 'Spotlight', folder: 'spotlight', category: 'UI', storybookTitle: 'UI/Spotlight', hasAutodocs: true, usageCount: 1, usagePages: ['buyer-summary'], status: 'niche', note: "Storybook title falls outside the 'Design System/*' taxonomy — naming inconsistency." },
  { name: 'Search Bar Multi', folder: 'search-bar-multi', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Search Bar Multi', hasAutodocs: true, usageCount: 1, usagePages: ['search'], status: 'niche' },
  { name: 'More Criteria', folder: 'more-criteria', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/More Criteria', hasAutodocs: true, usageCount: 1, usagePages: ['search'], status: 'niche' },
  { name: 'Result Card', folder: 'result-card', category: 'Data Display', storybookTitle: 'Design System/Data Display/Result Card', hasAutodocs: true, usageCount: 1, usagePages: ['search'], status: 'niche' },
  { name: 'Date Range', folder: 'date-range', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Date Range', hasAutodocs: true, usageCount: 1, usagePages: null, status: 'niche' },
  { name: 'Search Bar', folder: 'search-bar', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Search Bar', hasAutodocs: true, usageCount: 1, usagePages: ['home'], status: 'niche', note: "Confirmed distinct from Search Bar Multi (checked by hand, not a duplicate)." },
  { name: 'Action Card', folder: 'action-card', category: 'Data Display', storybookTitle: 'Design System/Data Display/Action Card', hasAutodocs: true, usageCount: 1, usagePages: ['admin-data'], status: 'niche', note: "Corrected on 2026-08-26 — the initial audit listed it as an orphan (0 usage), but it's actually used (selectable variant) in admin-data.component.html:118, the activity picker." },
  { name: 'Filter Drawer', folder: 'filter-drawer', category: 'Layout', storybookTitle: 'Design System/Layout/Filter Drawer', hasAutodocs: true, usageCount: 2, usagePages: null, status: 'niche' },
  { name: 'Radio Card', folder: 'radio-card', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Radio Card', hasAutodocs: true, usageCount: 2, usagePages: null, status: 'niche' },
  { name: 'Stepper', folder: 'stepper', category: 'Navigation', storybookTitle: 'Design System/Navigation/Stepper', hasAutodocs: true, usageCount: 2, usagePages: ['company-creation-wizard', 'company-edit-wizard'], status: 'niche' },
  { name: 'Tag Filter Chip', folder: 'tag-filter-chip', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Tag Filter Chip', hasAutodocs: true, usageCount: 1, usagePages: ['tag-configuration (via rule-modal)'], status: 'niche', note: "Promoted from pages/tag-configuration/components/ on 2026-08-26 — was already well built, just never moved." },

  // ── Chip vs Tag vs Badge: distinct in Figma — not a duplicate, don't merge ──
  { name: 'Chip', folder: 'chip', category: 'Action', storybookTitle: 'Design System/Action/Chip', hasAutodocs: true, usageCount: 1, usagePages: ['tag-filter-chip (internal)'], status: 'internal', note: "The initial audit compared it to Tag on API alone (similar props/ARIA) — but Chip, Tag and Badge are 3 distinct components in Figma. Source of truth is Figma, not code: not a merge to make, despite the surface resemblance." },
  { name: 'Tag', folder: 'tag', category: 'Action', storybookTitle: 'Design System/Action/Tag', hasAutodocs: true, usageCount: null, usagePages: ['properties-panel (internal)', 'action-card (internal)'], status: 'internal' },

  // ── Select Button / Tile: re-qualified — not a duplicate (distinct visual specs) ──
  { name: 'Select Button', folder: 'select-button', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Select Button', hasAutodocs: true, usageCount: 0, usagePages: null, status: 'orphan', note: "The initial audit called it a duplicate of Tile (similar API), but their visual specs are distinct: Select Button = 160px bordered rectangle + optional sublabel; Tile = fixed 104×104 square, no border. Likely two different Figma components, not a duplicate. Orphan (0 usage) still holds." },
  { name: 'Tile', folder: 'tile', category: 'Action', storybookTitle: 'Design System/Action/Tile', hasAutodocs: true, usageCount: 0, usagePages: null, status: 'orphan', note: 'See Select Button — re-qualified, not a duplicate.' },

  // ── Orphans: built, storied, never adopted ──────────────────────────────
  { name: 'Timeline Event', folder: 'timeline', category: 'Internals', storybookTitle: 'Design System/Internals/Timeline Event', hasAutodocs: true, usageCount: 0, usagePages: null, status: 'orphan' },
  { name: 'Toggle', folder: 'toggle', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Toggle', hasAutodocs: true, usageCount: 0, usagePages: null, status: 'orphan' },
  { name: 'Popover', folder: 'popover', category: 'Feedback', storybookTitle: 'Design System/Feedback/Popover', hasAutodocs: true, usageCount: 0, usagePages: null, status: 'orphan' },
  { name: 'Flyout (base panel)', folder: 'flyout', category: 'Layout', storybookTitle: 'Design System/Layout/Flyout', hasAutodocs: true, usageCount: 0, usagePages: null, status: 'orphan', note: 'Flyout Menu (which uses it internally) is well adopted — only the base panel, used directly, isn\'t.' },

  // ── Internal composites (used only through another DS component) ───────
  { name: 'Flyout Item', folder: 'flyout', category: 'Internals', storybookTitle: 'Design System/Internals/Flyout Item', hasAutodocs: true, usageCount: null, usagePages: null, status: 'internal' },
  { name: 'Flyout Section', folder: 'flyout', category: 'Internals', storybookTitle: 'Design System/Internals/Flyout Section', hasAutodocs: true, usageCount: null, usagePages: null, status: 'internal' },
  { name: 'Icon Tile', folder: 'icon-tile', category: 'Foundation', storybookTitle: 'Design System/Foundation/Icon Tile', hasAutodocs: true, usageCount: null, usagePages: ['result-card (internal)', 'action-card (internal)'], status: 'internal' },
  { name: 'Modal Content', folder: 'modal', category: 'Internals', storybookTitle: 'Design System/Internals/Modal Content', hasAutodocs: true, usageCount: null, usagePages: null, status: 'internal' },
  { name: 'Modal Header', folder: 'modal', category: 'Internals', storybookTitle: 'Design System/Internals/Modal Header', hasAutodocs: true, usageCount: null, usagePages: null, status: 'internal' },
  { name: 'Modal Footer', folder: 'modal', category: 'Internals', storybookTitle: 'Design System/Internals/Modal Footer', hasAutodocs: true, usageCount: null, usagePages: null, status: 'internal' },
  { name: 'Side Nav Item', folder: 'side-nav', category: 'Internals', storybookTitle: 'Design System/Internals/Side Nav Item', hasAutodocs: true, usageCount: null, usagePages: ['side-nav (internal)'], status: 'internal' },

  // ── Rest of the catalogue: never mentioned in the audits (no issue flagged) ──
  { name: 'Accordion', folder: 'accordion', category: 'Data Display', storybookTitle: 'Design System/Data Display/Accordion', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Button Range', folder: 'button-range', category: 'Action', storybookTitle: 'Design System/Action/Button Range', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Button Range Group', folder: 'button-range', category: 'Action', storybookTitle: 'Design System/Action/Button Range Group', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Checkbox Card', folder: 'checkbox-card', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Checkbox Card', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Collapsible Table', folder: 'collapsible-table', category: 'Data Display', storybookTitle: 'Design System/Data Display/Collapsible Table', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: "Its story hand-writes an HTML table of raw CSS tokens to document 'Design Tokens' — no shared addon behind it, risk of drift from the real tokens." },
  { name: 'Popin (Confirm Dialog)', folder: 'confirm-dialog', category: 'Feedback', storybookTitle: 'Design System/Feedback/Popin', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Divider', folder: 'divider', category: 'Foundation', storybookTitle: 'Design System/Foundation/Divider', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Flag', folder: 'flag', category: 'Foundation', storybookTitle: 'Design System/Foundation/Flag', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Functional Notice', folder: 'functional-notice', category: 'Feedback', storybookTitle: 'Design System/Feedback/Functional Notice', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Inline Edit', folder: 'inline-edit', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Inline Edit', hasAutodocs: false, usageCount: null, usagePages: null, status: 'niche', note: "Not detailed in the audit. Story has no 'autodocs' tag — links to the Default story instead of the docs page." },
  { name: 'Input Date', folder: 'input-date', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Input Date', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Input Email', folder: 'input-email', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Input Email', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'List Widget', folder: 'list-widget', category: 'Data Display', storybookTitle: 'Design System/Data Display/List Widget', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Pagination', folder: 'pagination', category: 'Action', storybookTitle: 'Design System/Action/Pagination', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Progress Bar', folder: 'progress-bar', category: 'Feedback', storybookTitle: 'Design System/Feedback/Progress Bar', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Radio', folder: 'radio', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Radio', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Cell Action', folder: 'table', category: 'Data Display/Table', storybookTitle: 'Design System/Data Display/Table/Cell Action', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Cell Selection', folder: 'table', category: 'Data Display/Table', storybookTitle: 'Design System/Data Display/Table/Cell Selection', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Textarea', folder: 'textarea', category: 'Data Entry', storybookTitle: 'Design System/Data Entry/Textarea', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Timeline', folder: 'timeline', category: 'Data Display', storybookTitle: 'Design System/Data Display/Timeline', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Toaster', folder: 'toaster', category: 'Feedback', storybookTitle: 'Design System/Feedback/Toaster', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche' },
  { name: 'Tooltip', folder: 'tooltip', category: 'Feedback', storybookTitle: 'Design System/Feedback/Tooltip', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Topbox', folder: 'topbox', category: 'Layout', storybookTitle: 'Design System/Layout/Topbox', hasAutodocs: true, usageCount: 1, usagePages: ['topbox (demo)'], status: 'niche' },
  { name: 'Visual Button', folder: 'visual-button', category: 'Action', storybookTitle: 'Design System/Action/Visual Button', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche', note: 'Not detailed in the audit.' },
  { name: 'Snackbar', folder: 'snackbar', category: 'Feedback', storybookTitle: 'Design System/Feedback/Snackbar', hasAutodocs: true, usageCount: null, usagePages: null, status: 'niche' },
];

export interface MutualizationTarget {
  title: string;
  description: string;
  occurrences: string[];
  effort: 'low' | 'medium' | 'high';
  /** On hold per product decision — see note. Not abandoned, just not prioritized. */
  onHold?: string;
}

export const MUTUALIZATION_TARGETS: MutualizationTarget[] = [
  {
    title: 'Wizard shell',
    description: "Whole structure duplicated identically: .wizard__cols/steps/panel/row/card/group/footer, the same ds-stepper, the same Back/Next footer, the same step types (address, contacts, activities...). Never extracted into a ds-wizard molecule.",
    occurrences: [
      'pages/search/company-creation-wizard/company-creation-wizard.component.html',
      'pages/admin-data/company-edit-wizard/company-edit-wizard.component.html',
    ],
    effort: 'high',
    onHold: "On hold as of 2026-08-26 — none of these 3 patterns are being mutualized right now.",
  },
  {
    title: 'Clickable option row',
    description: "Icon + label + secondary info, clickable — recoded independently 3 times. 2 of the 3 already live in the DS without knowing about each other.",
    occurrences: [
      'shared/ui/search-bar/search-bar.component.html (flyout item)',
      'shared/ui/spotlight/spotlight.component.html (row)',
      'pages/search/search.component.html (recent-search row)',
    ],
    effort: 'medium',
    onHold: "On hold as of 2026-08-26 — none of these 3 patterns are being mutualized right now.",
  },
  {
    title: 'Empty state',
    description: 'Icon + message + optional CTA, the same shape repeated with no shared atom.',
    occurrences: [
      'pages/search/search.component.html (×4)',
      'pages/tag-configuration/tag-configuration.component.html (×2)',
    ],
    effort: 'medium',
    onHold: "On hold as of 2026-08-26 — none of these 3 patterns are being mutualized right now.",
  },
  {
    title: 'Native buttons in buyer-summary',
    description: "The initial audit assumed ~17 native <button>s were reusable as-is (ds-tab, ds-tile, ds-radio-card, ds-checkbox-card, ds-button-icon, ds-segmented-control). Checked CSS-by-CSS on 2026-08-26: every button has a deliberate bespoke style (dashed borders on CTAs, dimensions/indicator different from ds-tab, own shapes for the size/layout/block pickers). None is a pixel-perfect swap without changing the render — same pattern as Select Button/Tile.",
    occurrences: ['pages/buyer-summary/buyer-summary.component.html'],
    effort: 'medium',
    onHold: "Decision from 2026-08-26: these buttons aren't forced into DS atoms without a prior Figma/visual check — risk of changing the render.",
  },
  {
    title: 'File upload',
    description: "Native <input type=\"file\"> — a genuine gap, no file-upload atom exists in the DS.",
    occurrences: ['pages/tag-configuration/components/import-rules-modal.component.html'],
    effort: 'medium',
  },
];

// Research from 2026-08-26: for each orphan, is there a native pattern in
// pages/** that could reasonably adopt it? Checked CSS-by-CSS before
// suggesting anything — after the Select Button/Tile lesson, a shape
// resemblance isn't enough, it needs a real visual match. Rendered as a
// left/right visual comparison directly in the dashboard's template
// (design-system-audit.component.html), not here as text — avoids two
// sources of truth for the same content.

export function storybookSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Dev: `npm run storybook` serves on its own port (6006), separate from
 * `ng serve` (4200) — there is no /storybook path locally. Prod: the
 * GitHub Pages build nests the static Storybook output under /storybook
 * inside this very app, so it must be reached relative to <base href>.
 */
export function storybookHref(
  entry: DsComponentEntry,
  opts: { baseURI: string; devMode: boolean },
): string | null {
  if (!entry.storybookTitle) return null;
  const slug = storybookSlug(entry.storybookTitle);
  const page = entry.hasAutodocs ? `/docs/${slug}--docs` : `/story/${slug}--default`;
  const base = opts.devMode ? 'http://localhost:6006/' : `${opts.baseURI}storybook/`;
  return `${base}?path=${page}`;
}

/**
 * meta.title -> id of the FIRST real story (not the autodocs page), for
 * embedding a live thumbnail. Extracted from `dist/storybook/index.json`
 * on 2026-08-26 (`npm run build-storybook`) — a snapshot, not computed at
 * runtime, since the app can't read Storybook's build manifest live.
 * Regenerate by rebuilding Storybook and re-running the same extraction
 * whenever component stories are added/renamed/reordered.
 */
const STORYBOOK_FIRST_STORY_ID: Record<string, string> = {
  'Design System/Data Display/Accordion': 'design-system-data-display-accordion--playground',
  'Design System/Data Display/Action Card': 'design-system-data-display-action-card--default',
  'Design System/Feedback/Badge': 'design-system-feedback-badge--default',
  'Design System/Action/Breadcrumbs': 'design-system-action-breadcrumbs--default',
  'Design System/Action/Button Icon': 'design-system-action-button-icon--default',
  'Design System/Action/Button Range Group': 'design-system-action-button-range-group--range-mode',
  'Design System/Action/Button Range': 'design-system-action-button-range--default',
  'Design System/Action/Button Split': 'design-system-action-button-split--default',
  'Design System/Action/Button': 'design-system-action-button--primary',
  'Design System/Data Display/Card': 'design-system-data-display-card--default',
  'Design System/Data Display/Chart': 'design-system-data-display-chart--grade',
  'Design System/Data Entry/Checkbox Card': 'design-system-data-entry-checkbox-card--playground',
  'Design System/Data Entry/Checkbox': 'design-system-data-entry-checkbox--default',
  'Design System/Action/Chip': 'design-system-action-chip--static',
  'Design System/Data Display/Collapsible Table': 'design-system-data-display-collapsible-table--tokens',
  'Design System/Feedback/Popin': 'design-system-feedback-popin--warning',
  'Design System/Action/Crumb': 'design-system-action-crumb--default',
  'Design System/Data Entry/Date Range': 'design-system-data-entry-date-range--range-single-calendar',
  'Design System/Foundation/Divider': 'design-system-foundation-divider--horizontal',
  'Design System/Layout/Drawer': 'design-system-layout-drawer--default',
  'Design System/Layout/Filter Drawer': 'design-system-layout-filter-drawer--default',
  'Design System/Foundation/Flag': 'design-system-foundation-flag--france',
  'Design System/Internals/Flyout Menu Item': 'design-system-internals-flyout-menu-item--default',
  'Design System/Action/Flyout Menu': 'design-system-action-flyout-menu--four-actions',
  'Design System/Internals/Flyout Item': 'design-system-internals-flyout-item--default',
  'Design System/Internals/Flyout Section': 'design-system-internals-flyout-section--highlighted',
  'Design System/Layout/Flyout': 'design-system-layout-flyout--policies-flyout',
  'Design System/Feedback/Functional Notice': 'design-system-feedback-functional-notice--playground',
  'Design System/Data Display/Grade': 'design-system-data-display-grade--playground',
  'Design System/Data Entry/Grid Selection': 'design-system-data-entry-grid-selection--default',
  'Design System/Layout/Header': 'design-system-layout-header--qirin',
  'Design System/Foundation/Icon Tile': 'design-system-foundation-icon-tile--default',
  'Design System/Foundation/Icon': 'design-system-foundation-icon--default',
  'Design System/Data Entry/Inline Edit': 'design-system-data-entry-inline-edit--default',
  'Design System/Data Entry/Input Date': 'design-system-data-entry-input-date--playground',
  'Design System/Data Entry/Input Email': 'design-system-data-entry-input-email--playground',
  'Design System/Data Entry/Input Search': 'design-system-data-entry-input-search--playground',
  'Design System/Data Entry/Input Text': 'design-system-data-entry-input-text--default',
  'Design System/Action/Link': 'design-system-action-link--default',
  'Design System/Data Display/List Widget': 'design-system-data-display-list-widget--job-to-do',
  'Design System/Foundation/Logo': 'design-system-foundation-logo--default',
  'Design System/Internals/Modal Content': 'design-system-internals-modal-content--default',
  'Design System/Internals/Modal Footer': 'design-system-internals-modal-footer--full',
  'Design System/Internals/Modal Header': 'design-system-internals-modal-header--default',
  'Design System/Layout/Modal': 'design-system-layout-modal--medium',
  'Design System/Data Entry/More Criteria': 'design-system-data-entry-more-criteria--default',
  'Design System/Data Display/Newsfeed': 'design-system-data-display-newsfeed--default',
  'Design System/Layout/Page Header': 'design-system-layout-page-header--full',
  'Design System/Layout/Page Title': 'design-system-layout-page-title--default',
  'Design System/Action/Pagination': 'design-system-action-pagination--playground',
  'Design System/Data Display/Pie Chart': 'design-system-data-display-pie-chart--default',
  'Design System/Feedback/Popover': 'design-system-feedback-popover--playground',
  'Design System/Feedback/Progress Bar': 'design-system-feedback-progress-bar--default',
  'Design System/Data Display/Properties Panel': 'design-system-data-display-properties-panel--two-columns-cards',
  'Design System/Data Entry/Radio Card': 'design-system-data-entry-radio-card--playground',
  'Design System/Data Entry/Radio': 'design-system-data-entry-radio--default',
  'Design System/Data Display/Result Card': 'design-system-data-display-result-card--closed',
  'Design System/Data Entry/Search Bar Multi': 'design-system-data-entry-search-bar-multi--default',
  'Design System/Data Entry/Search Bar': 'design-system-data-entry-search-bar--default',
  'Design System/Action/Segmented Control': 'design-system-action-segmented-control--playground',
  'Design System/Data Entry/Select Button': 'design-system-data-entry-select-button--playground',
  'Design System/Data Entry/Select': 'design-system-data-entry-select--default',
  'Design System/Internals/Side Nav Item': 'design-system-internals-side-nav-item--default',
  'Design System/Layout/Side Nav': 'design-system-layout-side-nav--default',
  'Design System/Feedback/Skeleton Item': 'design-system-feedback-skeleton-item--text-lines',
  'Design System/Feedback/Snackbar': 'design-system-feedback-snackbar--default',
  'Design System/Feedback/Spinner': 'design-system-feedback-spinner--default',
  'Design System/Action/Standalone Dropdown': 'design-system-action-standalone-dropdown--default',
  'Design System/Navigation/Stepper': 'design-system-navigation-stepper--default',
  'Design System/Action/Tab': 'design-system-action-tab--default',
  'Design System/Data Display/Table/Cell Action': 'design-system-data-display-table-cell-action--default',
  'Design System/Data Display/Table/Cell Header': 'design-system-data-display-table-cell-header--default',
  'Design System/Data Display/Table/Cell Selection': 'design-system-data-display-table-cell-selection--check',
  'Design System/Data Display/Table/Cell': 'design-system-data-display-table-cell--default',
  'Design System/Data Display/Table/Table Row': 'design-system-data-display-table-table-row--default',
  'Design System/Data Entry/Tag Filter Chip': 'design-system-data-entry-tag-filter-chip--chip',
  'Design System/Action/Tag': 'design-system-action-tag--static',
  'Design System/Data Entry/Textarea': 'design-system-data-entry-textarea--default',
  'Design System/Action/Tile': 'design-system-action-tile--playground',
  'Design System/Internals/Timeline Event': 'design-system-internals-timeline-event--default',
  'Design System/Data Display/Timeline': 'design-system-data-display-timeline--default',
  'Design System/Feedback/Toaster': 'design-system-feedback-toaster--playground',
  'Design System/Data Entry/Toggle': 'design-system-data-entry-toggle--default',
  'Design System/Feedback/Tooltip': 'design-system-feedback-tooltip--static',
  'Design System/Layout/Topbox': 'design-system-layout-topbox--buyer-full',
  'Design System/Action/Visual Button': 'design-system-action-visual-button--default',
  'Design System/Data Display/Widget Card': 'design-system-data-display-widget-card--figures',
  'UI/Spotlight': 'ui-spotlight--empty',
};

/** Live embed of the component's first story — the visual, not a description. */
export function storybookIframeSrc(
  entry: DsComponentEntry,
  opts: { baseURI: string; devMode: boolean },
): string | null {
  if (!entry.storybookTitle) return null;
  const storyId = STORYBOOK_FIRST_STORY_ID[entry.storybookTitle];
  if (!storyId) return null;
  const base = opts.devMode ? 'http://localhost:6006/' : `${opts.baseURI}storybook/`;
  return `${base}iframe.html?id=${storyId}&viewMode=story`;
}
